version: "3.8"

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=false
      - DATABASE_URL=postgresql://postgres:password@db:5432/empirica
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LAVA_SECRET_KEY=${LAVA_SECRET_KEY}
      - LAVA_CONNECTION_SECRET=${LAVA_CONNECTION_SECRET}
      - LAVA_PRODUCT_SECRET=${LAVA_PRODUCT_SECRET}
      - ENABLE_LAVA=${ENABLE_LAVA:-false}
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=empirica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
