services:
  # Backend API Service
  - type: web
    name: synapse-mapper-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: synapse-mapper-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://synapse-mapper-frontend.onrender.com
      - key: ENABLE_LLM_EXTRACTION
        value: false
      - key: MAX_UPLOAD_SIZE_MB
        value: 50
      - key: MAX_CONCURRENT_PROCESSING
        value: 2
    healthCheckPath: /
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: synapse-mapper-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    plan: starter
    region: oregon
    envVars:
      - key: VITE_API_URL
        value: https://synapse-mapper-api.onrender.com
    autoDeploy: true

databases:
  - name: synapse-mapper-db
    plan: starter
    region: oregon
